# Generated by Django 4.2.9 on 2024-01-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_basemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
