# Generated by Django 4.2.9 on 2024-01-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_category_contact_experience_portfolioimage_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='text',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='age',
            field=models.SmallIntegerField(),
        ),
    ]
