# Generated by Django 4.2.9 on 2024-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_myinfo_text_alter_myinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='degree',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
