# Generated by Django 4.2.9 on 2024-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_experience_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='finished',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
